### ISSUE TITLE
Tensorflow bug

### ISSUE THREAD

**Issue by wbwvos** [tkipf/kegra#1]
Hi Thomas,

I've tried to run the train.py code. When using Theano as a backend it works but when I try to use Tensorflow it breaks. I've changed nothing in the source code but the code still breaks. Do you happen to know why this is the case? Or is Tensorflow just not supported yet?

` python train.py
  Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5.1.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.8.0 locally
Loading cora dataset...
Dataset has 2708 nodes, 5429 edges, 1432 features.
Using local pooling filters...
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 960M
major: 5 minor: 0 memoryClockRate (GHz) 1.176
pciBusID 0000:01:00.0
Total memory: 3.95GiB
Free memory: 3.54GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0)
Traceback (most recent call last):
  File "train.py", line 76, in <module>
    batch_size=A.shape[0], nb_epoch=1, shuffle=False, verbose=0)
  File "/home/wolf/anaconda2/envs/tf_gpu/lib/python2.7/site-packages/keras/engine/training.py", line 1124, in fit
    callback_metrics=callback_metrics)
  File "/home/wolf/anaconda2/envs/tf_gpu/lib/python2.7/site-packages/keras/engine/training.py", line 842, in _fit_loop
    outs = f(ins_batch)
  File "/home/wolf/anaconda2/envs/tf_gpu/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1040, in __call__
    updated = session.run(self.outputs + [self.updates_op], feed_dict=feed_dict)
  File "/home/wolf/anaconda2/envs/tf_gpu/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/home/wolf/anaconda2/envs/tf_gpu/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 945, in _run
    raise ValueError('Tensor %s may not be fed.' % subfeed_t)
ValueError: Tensor Output("Const:0", shape=(2,), dtype=int64) may not be fed.
`

**Comment by tkipf** [comment]
Thanks for catching this. This seems to be an issue related to TensorFlow versions later than v. 0.11 and how the feed_dict is constructed, but I think the latest version of keras should fix this. Can you try upgrading keras?

**Comment by wbwvos** [comment]
That does the trick indeed. I misread the requirements.
