### ISSUE TITLE
Deprecated Keras API

### ISSUE THREAD

**Issue by bkj** [tkipf/kegra#2]
Using `keras-1.2.2` raises this warning on `python train.py`:

```
Using Theano backend.
Using gpu device 0: TITAN X (Pascal) (CNMeM is enabled with initial size: 25.0% of memory, cuDNN 5110)
/home/bjohnson/.anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py:600: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.
  warnings.warn(warn)
Loading cora dataset...
Dataset has 2708 nodes, 5429 edges, 1432 features.
/home/bjohnson/.anaconda/lib/python2.7/site-packages/keras/engine/topology.py:379: UserWarning: The `regularizers` property of layers/models is deprecated. Regularization losses are now managed via the `losses` layer/model property.
  warnings.warn('The `regularizers` property of layers/models '
```

And experiments show that the `W_regularizer` parameter in `GraphConvolution` does not have the expected effect.  Looks like Keras changed the way that regularizers get attached to weight matrices, but I'm not sure what best practices on the new API are.  Presumably could copy from

https://github.com/fchollet/keras/blob/master/keras/layers/core.py#L654

**Comment by tkipf** [comment]
Thanks for catching this. Commit https://github.com/tkipf/kegra/commit/00db558563b5d8b6a5d2f0ec0a516568f46efcd1 takes care of this now!
