### ISSUE TITLE
Graph Convolution Layer Correct?

### ISSUE THREAD

**Issue by why94nb** [tkipf/kegra#35]
Hey,
I must misunderstand your code about graph convolution layer. Is graph convolution implemented within graph.py? I know in your tf version, there's this chunk of code commented by #convolve in layers.py. So what is the corresponding part in graph.py? Thank you for your time.

**Comment by why94nb** [comment]
I guess I was not clear about my question..
I mean, I am trying to understand how the adjacency matrix is involved in this code? Anyone can explain this for me? Appreciate it.

**Comment by tkipf** [comment]
The convolution happens in the ‚call‘ method. The adjacency matrix (or matrices) are summarized in the variable ‚supports‘. Hope this helps.
