### ISSUE TITLE
Negative values in the adjacency matrix and the feature matrix

### ISSUE THREAD

**Issue by basma-b** [tkipf/kegra#39]
Hello @tkipf 

Are we allowed to have negative values in the adjacency matrix ?
The same question for the feature matrix ?

**Comment by tkipf** [comment]
Feature matrix: yes, no problem. For the adjacency matrix this can be
problematic as the normalization constants can become 0 in this case (apart
from the fact that also the spectral interpretation we offer in the paper
breaks down).
